name: 'Deploy Docker image'

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: The docker image tag you want to use.
        required: true
        default: v1.0.0
      docker_image_name:
        description: Specify your docker image name. This represents the folder in the repo structure.
        required: true
        default: magic-ball

jobs:
  deploy_docker_image:
    name: "Deploy docker image"
    runs-on: ${{ matrix.os }}
    env:
      image_tag: "${{ github.event.inputs.docker_image_tag }}"
      image_name: "${{ github.event.inputs.docker_image_name }}"
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]

    steps:
      - uses: actions/checkout@v2

      - name: "Set Build Persistent Variables and Dockerfile"
        shell: bash
        run: |
          source libraries/utilities/set_persistent_library_path

      - name: "SSH into EC2 Instance and Deploy App"
        shell: bash
        env:
          key: "${{ secrets.SECRET_SSH_KEY }}"
          EC2_INSTANCE_USERNAME: "${{ secrets.INSTANCE_USERNAME }}"
          INSTANCE_DNS_NAME: "${{ secrets.INSTANCE_DNS_NAME }}"
        run: |
          set +x
          bash SSH_EC2_deploy_app.sh